<?php

define('DBSERV','localhost');
define('DBUSER','cardsmaster');
define('DBPASS','cardsmaster129!');
define('DBNAME','cards');
define('TABLE_USERS','cards.users');
define('TABLE_USERLOGS','cards.userlogs');
define('TABLE_LISTS','cards.lists');
define('TABLE_CLIENTS','cards.masterfile');
define('TABLE_CLIENTINFO','cards.clientinfo');
define('TABLE_SEARCH','cards.searchfields');
define('TABLE_HISTORY','cards.callhistory');
define('TABLE_CARDS','cards.cardchoice');
define('TABLE_DISPO','cards.dispositions');
define('TABLE_FILES','cards.docs');
define('TABLE_PHONES','cards.phonenumbers');
define('TABLE_AGENTDASH','cards.agentdashboard');
define('TABLE_VER','cards.verifications');
define('TABLE_TURNIN','cards.turnins');
define('TABLE_ACD','cards.appcandec');
define('DIAL_PREFIX','7277');
?>